# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'front.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from registration  import *
from showProcess import *

class Ui_StudentProductivityBooster(object):
    def setupUi(self, StudentProductivityBooster):
        StudentProductivityBooster.setObjectName("StudentProductivityBooster")
        StudentProductivityBooster.resize(675, 444)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(StudentProductivityBooster.sizePolicy().hasHeightForWidth())
        StudentProductivityBooster.setSizePolicy(sizePolicy)
        StudentProductivityBooster.setStyleSheet("background-color: rgb(224, 249, 255);")
        StudentProductivityBooster.setAnimated(True)
        self.centralwidget = QtWidgets.QWidget(StudentProductivityBooster)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet(" \n"
"background-color: rgb(224, 249, 255);")
        self.label.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.btn_registration = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_registration.sizePolicy().hasHeightForWidth())
        self.btn_registration.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.btn_registration.setFont(font)
        self.btn_registration.setStyleSheet(" \n"
"background-color: rgb(170, 170, 127);")
        self.btn_registration.setObjectName("btn_registration")
        self.horizontalLayout_2.addWidget(self.btn_registration)
        self.btn_processing = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_processing.sizePolicy().hasHeightForWidth())
        self.btn_processing.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.btn_processing.setFont(font)
        self.btn_processing.setStyleSheet("background-color: rgb(3, 201, 255);\n"
"background-color: rgb(170, 170, 127);")
        self.btn_processing.setObjectName("btn_processing")
        self.horizontalLayout_2.addWidget(self.btn_processing)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout.addLayout(self.verticalLayout)
        StudentProductivityBooster.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(StudentProductivityBooster)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 675, 21))
        self.menubar.setObjectName("menubar")
        StudentProductivityBooster.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(StudentProductivityBooster)
        self.statusbar.setObjectName("statusbar")
        StudentProductivityBooster.setStatusBar(self.statusbar)

        self.retranslateUi(StudentProductivityBooster)
        QtCore.QMetaObject.connectSlotsByName(StudentProductivityBooster)
        self.btn_registration.clicked.connect(self.registerForm)
        self.btn_processing.clicked.connect(self.processingForm)


    def registerForm(self): 
        self.Registerform = QtWidgets.QMainWindow()
        self.ui = Ui_Registerform()
        self.ui.setupUi(self.Registerform)
        self.Registerform.show()
    def processingForm(self): 
        self.Dialog = QtWidgets.QDialog()
        self.ui = Ui_Dialog()
        self.ui.setupUi(self.Dialog)
        self.Dialog.show()
             
            

  
        

    def retranslateUi(self, StudentProductivityBooster):
        _translate = QtCore.QCoreApplication.translate
        StudentProductivityBooster.setWindowTitle(_translate("StudentProductivityBooster", "MainWindow"))
        self.label.setText(_translate("StudentProductivityBooster", "Smart Classroom"))
        self.btn_registration.setText(_translate("StudentProductivityBooster", "Registration"))
        self.btn_processing.setText(_translate("StudentProductivityBooster", "Processing"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    StudentProductivityBooster = QtWidgets.QMainWindow()
    ui = Ui_StudentProductivityBooster()
    ui.setupUi(StudentProductivityBooster)
    StudentProductivityBooster.show()
    sys.exit(app.exec_())
