# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'registration.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import os
import cv2
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import (QWidget,QFileDialog, QPushButton, QLineEdit,QAction,
                             QInputDialog, QApplication)

class Ui_Registerform(object):
    def setupUi(self, Registerform):
        Registerform.setObjectName("Registerform")
        Registerform.resize(498, 475)
        Registerform.setStyleSheet("\n"
"background-color: rgb(224, 249, 255);")
        self.centralwidget = QtWidgets.QWidget(Registerform)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_img = QtWidgets.QLabel(self.centralwidget)
        self.label_img.setAlignment(QtCore.Qt.AlignCenter)
        self.label_img.setObjectName("label_img")
        self.horizontalLayout.addWidget(self.label_img)
        self.btn_upload = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.btn_upload.setFont(font)
        self.btn_upload.setStyleSheet("background-color: rgb(170, 170, 127);")
        self.btn_upload.setObjectName("btn_upload")
        self.horizontalLayout.addWidget(self.btn_upload)
        self.gridLayout_2.addLayout(self.horizontalLayout, 6, 1, 1, 1)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.lineEdit_name = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_name.setObjectName("lineEdit_name")
        self.gridLayout.addWidget(self.lineEdit_name, 0, 2, 1, 1)
        self.lineEdit_rollNo = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_rollNo.setObjectName("lineEdit_rollNo")
        self.gridLayout.addWidget(self.lineEdit_rollNo, 1, 2, 1, 1)
        self.label_rollNo = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_rollNo.setFont(font)
        self.label_rollNo.setObjectName("label_rollNo")
        self.gridLayout.addWidget(self.label_rollNo, 1, 1, 1, 1)
        self.label_name = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_name.setFont(font)
        self.label_name.setObjectName("label_name")
        self.gridLayout.addWidget(self.label_name, 0, 1, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 1, 1, 1, 1)
        self.btn_register = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.btn_register.setFont(font)
        self.btn_register.setStyleSheet("background-color: rgb(170, 170, 127);")
        self.btn_register.setObjectName("btn_register")
        self.gridLayout_2.addWidget(self.btn_register, 7, 1, 1, 1)
        Registerform.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(Registerform)
        self.statusbar.setObjectName("statusbar")
        Registerform.setStatusBar(self.statusbar)
        self.btn_upload.clicked.connect(self.browsing)


        self.retranslateUi(Registerform)
        QtCore.QMetaObject.connectSlotsByName(Registerform)
    def browsing(self):
        Namevalue=self.lineEdit_name.text()
        Idvalue=self.lineEdit_rollNo.text()
        path=r'C:/Users/Shiza/Pictures/Camera Roll' 
        fname=QFileDialog.getOpenFileName(None,"Select a file...",path)
        #name='anum'  
        #print(str(fname[0]))
        #path1=r(fname[0]) 
        #img=cv2.imread(fname[0])
        #cv2.imshow("helo",img)
        #cv2.imwrite("savedImage2.jpg",img)

        
        img=cv2.imread(fname[0])
        base_dir="TrainingImage"   
        
        p=os.path.join(base_dir, Namevalue)
        print(p)
        p2="\ " 
        p1=p+p2
     
        print(p1)
        cv2.imwrite(p1+Namevalue  +"."+Idvalue+ ".jpeg", img)   
        path1=r'C:/Users/Shiza/TrainingImage'
        os.chdir(path1)
         
        print(os.path)
        if not os.path.exists(Namevalue):
            os.makedirs(Namevalue)
        #self.my(img,p1)
        
        print( str(fname[0]))
        

    def retranslateUi(self, Registerform):
        _translate = QtCore.QCoreApplication.translate
        Registerform.setWindowTitle(_translate("Registerform", "MainWindow"))
        self.label_img.setText(_translate("Registerform", "Image"))
        self.btn_upload.setText(_translate("Registerform", "Upload"))
        self.label_rollNo.setText(_translate("Registerform", "Roll no     "))
        self.label_name.setText(_translate("Registerform", "Name      "))
        self.btn_register.setText(_translate("Registerform", "Register"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Registerform = QtWidgets.QMainWindow()
    ui = Ui_Registerform()
    ui.setupUi(Registerform)
    Registerform.show()
    sys.exit(app.exec_())
